REDMINE-24948 : IDSv3 - global refactoring : add service contract man…
lutece-secteur-public/gru-plugin-identitystore pull request #6
Opened 2023-02-06 17:48 UTC by lobtx

…agement

2023-02-09 18:17 UTC, seboo requested changes
une question plus générale, par rapport aux contrôles de droits et aux services :
est-ce que les contrôles doivent se faire "avant" IdentityStoreService, "dedans", ou "après", dans IdentityService ?
je pense que c'est mieux de la faire au niveau de IdentityStoreService
on en rediscute

2023-02-09 18:17 UTC, seboo commented on src/sql/plugins/identitystore/plugin/create_db_identitystore.sql
> +CREATE TABLE identitystore_client_application_certifiers
on ne se sert plus de cette table, non ?

2023-02-09 18:17 UTC, seboo commented on src/sql/plugins/identitystore/plugin/create_db_identitystore.sql
> +    lastupdate_date        timestamp    NOT NULL default CURRENT_TIMESTAMP,
peut-être peut-on stocker le dernier id_history à la place des deux champs lastupdate_* ?

2023-02-09 18:17 UTC, seboo commented on src/sql/plugins/identitystore/plugin/create_db_identitystore.sql
> +    PRIMARY KEY (id_service_contract)
Il faudrait ajouter un droit de mise à jour du GUID

2023-02-09 18:17 UTC, seboo commented on src/sql/plugins/identitystore/upgrade/update_db_identitystore-2.0.11-2.0.12.sql
> +--
il faudrait renommer le fichier en  (...)2.0.11-3.0.0.sql
on pourra à terme ajouter ici les scripts de migration de données

2023-02-09 18:17 UTC, seboo commented on webapp/WEB-INF/conf/caches.dat
> +#Caches status file
on ne met pas ça dans le plugin, on pourra mettre ça dans le site

2023-02-09 18:17 UTC, seboo commented on pom.xml
> +			<version>7.0.0</version>
il faut mettre des range [7.0.0,)
si on met à partir de la 7.0.7, je pense qu'on a pas besoin d'exclure les lib Jackson

2023-02-09 18:17 UTC, seboo commented on pom.xml
> +			<version>3.2.1-SNAPSHOT</version>
il faut un range ouvert

2023-02-09 18:17 UTC, seboo commented on pom.xml
> +			<exclusions>
ce plugin ne ramène pas Jackson à priori ?

2023-02-09 18:17 UTC, seboo commented on pom.xml
> +			<version>3.0.0-SNAPSHOT</version>
idem

2023-02-09 18:17 UTC, seboo commented on pom.xml
> +			<groupId>org.apache.httpcomponents.client5</groupId>
la library  library-httpaccess ramène déjà cette dependance , non ?

2023-02-15 16:35 UTC, lobtx commented on src/java/fr/paris/lutece/plugins/identitystore/service/IdentityStoreService.java
> +            listIdentityDto.add( fr.paris.lutece.plugins.identitystore.v2.web.rs.DtoConverter.convertToDto( identity,
Exact mais le découplage n'étant pas encore fait il y a un DtoConverter par vx, mais je déplace les méthodes de la V3 dans IdentityService ce sera plus simple et on pourra supprimer complètement cette classe qui fait doublon

2023-02-15 16:49 UTC, lobtx commented on src/java/fr/paris/lutece/plugins/identitystore/service/contract/ServiceContractService.java
> +            this._cache.put( clientApplication.getCode( ), serviceContract );
il est partagé entre les instances ?

2023-02-16 13:56 UTC, lobtx commented on src/java/fr/paris/lutece/plugins/identitystore/service/identity/IdentityService.java
> +        final List<IdentityObject> identities = IdentityHome.findAll( ).stream( ).filter( i -> !i.isDeleted( ) && !i.isMerged( ) ).map(
Fait dans le service de réindexation qui batch avec une size définissable en conf + appels //

2023-02-16 13:57 UTC, lobtx commented on src/java/fr/paris/lutece/plugins/identitystore/service/identity/IdentityService.java
> +        final Response search = _identitySearcher.search( searchAttributes );
Effectivement il faut prévoir une pagination

2023-02-16 14:02 UTC, lobtx commented on src/java/fr/paris/lutece/plugins/identitystore/service/identity/IdentityService.java
> +            IdentityStoreNotifyListenerService.instance( ).notifyListenersAttributeChange( attributeChange );
Oui dans le getOrigin on récupère

@JsonProperty("author_name")
    protected String name;
    @JsonProperty("author_type")
    protected AuthorType type;

2023-02-16 14:18 UTC, lobtx commented on src/java/fr/paris/lutece/plugins/identitystore/service/identity/IdentityService.java
> +            response.setDuplicates( duplicates );
Effectivement je le retire, il me semble qu'on avait évoqué le fait de renvoyer éventuellement le customerId

2023-02-16 14:20 UTC, lobtx commented on src/java/fr/paris/lutece/plugins/identitystore/service/identity/IdentityService.java
> +                certificate.setCertificateLevel( Integer.parseInt( level ) );
Il est utilisé pour la comparaison des attributs dans les clients qui n'ont pas l'info de pondération des levels. A voir si l'onf mieux plus tard ?

2023-02-16 14:21 UTC, lobtx commented on src/java/fr/paris/lutece/plugins/identitystore/service/identity/IdentityService.java
> +                    final Map<String, AttributeObject> attributeObjects = this.mapToIndexObject( identity );
J'ai implémenté un IdentityChangeListerner qui s'en occupe

2023-02-16 14:27 UTC, lobtx commented on src/java/fr/paris/lutece/plugins/identitystore/service/identity/IdentityService.java
> +        // TODO calculer le taux de couverture
Il s'agirait d'un taux de couverture des exigences du contrat de service: level de l'attribut vs contrat de service. On l'a évoqué un temps mais ce n'et peut-être plus d'actualité ?

2023-02-16 14:30 UTC, lobtx commented on src/java/fr/paris/lutece/plugins/identitystore/service/indexer/elastic/client/ElasticClient.java
> +        return true;
Plutôt à faire dans le netscaler pour éviter de gérer les 3 noeuds master dans le client.

2023-02-16 14:32 UTC, lobtx commented on src/java/fr/paris/lutece/plugins/identitystore/service/indexer/elastic/index/business/IndexActionDao.java
> +        indexAction.setId( newPrimaryKey( plugin ) );
Il vaudrait même mieux utiliser la puissance des db qui le créent eux-même à l'insert et retournent l'id créé si besoin. Cela évitera même des problèmes d'éccès concurrents. Je propose de le traiter dans une phase de retours car il y a quelques DAO à dépoussiérer. On en profitera pour alléger les requêtes aussi notamment certains select gourmands.

2023-02-16 14:32 UTC, lobtx commented on src/java/fr/paris/lutece/plugins/identitystore/service/indexer/elastic/index/business/IndexActionDao.java
> +        final DAOUtil daoUtil = new DAOUtil( SQL_QUERY_SELECTALL_WITH_LIMIT, plugin );
Dans la version actuelle du code j'ai batché (comme pour le réindexing) donc le limit ne sert plus

2023-02-16 14:33 UTC, lobtx commented on src/java/fr/paris/lutece/plugins/identitystore/service/indexer/elastic/index/business/IndexActionDao.java
> +        indexAction.setId( newPrimaryKey( plugin ) );
Il faudrait mettre à jour le plugin wizard aussi pour qu'il ne le génère pas si je ne dis pas de bêtise.

2023-02-16 14:33 UTC, lobtx commented on src/java/fr/paris/lutece/plugins/identitystore/v1/web/rs/IdentityRequestValidator.java
> +            List<AttributeRight> lstRights = ServiceContractHome.findByPrimaryKey( nServiceContractId ).map( ServiceContractHome::selectApplicationRights )
Oui à supprimer lors du portage vers v3

2023-02-16 14:34 UTC, lobtx commented on src/java/fr/paris/lutece/plugins/identitystore/v1/web/rs/IdentityRequestValidator.java
> +    public void checkAttributes( IdentityDto identityDto, String strClientAppCode, int nServiceContractId, Map<String, File> mapAttachedFiles )
Oui c'est la tendence pour la V3, à faire pour le portage

2023-02-16 14:35 UTC, lobtx commented on src/java/fr/paris/lutece/plugins/identitystore/v2/web/request/IdentityStoreAppRightsRequest.java
>              throw new AppException( ERROR_JSON_MAPPING, e );
Non effectivement il faudra faire une passe sur la gestion des exceptions dans la phase de retours

2023-02-16 14:35 UTC, lobtx commented on src/java/fr/paris/lutece/plugins/identitystore/v2/web/rs/IdentityRequestValidator.java
> +            List<AttributeRight> listRights = ServiceContractHome.findByPrimaryKey( nServiceContractId ).map( ServiceContractHome::selectApplicationRights )
Oui à traiter lors du portage. Par contre ils ne vont bien utiliser que le getIdentity ?

2023-02-16 14:38 UTC, lobtx commented on src/java/fr/paris/lutece/plugins/identitystore/web/AttributeKeyJspBean.java
> +        IdentityService.instance( ).createAttributeKey( _attributekey );
Oui c'est vrai ça se discute, je suis parti du principe qu'il serait bon de centraliser toutes les manipulations de BDD à traver les services de chaque domaine qui gèrent la synchro avec le cache. ça permet d'exposer plus clairement au dev les différents dispatchs.

2023-02-16 14:39 UTC, lobtx commented on src/sql/plugins/identitystore/plugin/create_db_identitystore.sql
> +CREATE TABLE identitystore_client_application_certifiers
Non je ne sais pas à quoi elle servait il faudra supprimer toute la branche concernée

2023-02-17 13:50 UTC, seboo commented on src/java/fr/paris/lutece/plugins/identitystore/service/IdentityStoreService.java
> +            listIdentityDto.add( fr.paris.lutece.plugins.identitystore.v2.web.rs.DtoConverter.convertToDto( identity,
ok

2023-02-17 13:55 UTC, seboo commented on src/java/fr/paris/lutece/plugins/identitystore/service/identity/IdentityService.java
> +                certificate.setCertificateLevel( Integer.parseInt( level ) );
ok, tant qu'on ne stocke pas les level au niveau des attributs

2023-02-17 13:56 UTC, seboo commented on src/java/fr/paris/lutece/plugins/identitystore/service/identity/IdentityService.java
> +            IdentityStoreNotifyListenerService.instance( ).notifyListenersAttributeChange( attributeChange );
ok

2023-02-17 14:06 UTC, seboo commented on src/java/fr/paris/lutece/plugins/identitystore/service/identity/IdentityService.java
> +        // TODO calculer le taux de couverture
effectivement, au final on a besoin de disposer des trois scores : qualité, correspondance, exigences

2023-02-17 14:07 UTC, seboo commented on src/java/fr/paris/lutece/plugins/identitystore/service/indexer/elastic/index/business/IndexActionDao.java
> +        indexAction.setId( newPrimaryKey( plugin ) );
ok, à vérifier pour le wizard

2023-02-17 14:09 UTC, seboo commented on src/java/fr/paris/lutece/plugins/identitystore/v1/web/rs/IdentityRequestValidator.java
> +    public void checkAttributes( IdentityDto identityDto, String strClientAppCode, int nServiceContractId, Map<String, File> mapAttachedFiles )
ok

2023-02-17 14:09 UTC, seboo commented on src/java/fr/paris/lutece/plugins/identitystore/v2/web/rs/IdentityRequestValidator.java
> +            List<AttributeRight> listRights = ServiceContractHome.findByPrimaryKey( nServiceContractId ).map( ServiceContractHome::selectApplicationRights )
oui

2023-02-17 14:13 UTC, seboo commented on src/java/fr/paris/lutece/plugins/identitystore/web/AttributeKeyJspBean.java
> +        IdentityService.instance( ).createAttributeKey( _attributekey );
Le principe qu'on a adopté, c'est que la classe Home* peut être utilisée par le plugin dans laquelle est déclarée, et que les autres plugins / modules utilisent plutôt la classe Service.
A priori les autres plugins / modules ne feront pas de création d'attributs

2023-03-02 17:16 UTC, merged